### ISSUE TITLE
简单模块

### ISSUE THREAD

**Issue by ajccom** [ajccom/note#2]
```javascript
// input event
ipt.on('input', function () {
  check(this)
})
        
ipt.on('compositionend', function () {
  check(this)
})
        
ipt.on('blur', function () {
  check(this)
})

// fps
var fps = (function () {
          var f = 60, t = 1000 / f, time = Date.now()
          
          function check () {
            var temp = Date.now()
            if (temp - time > t) {
              time = temp
              return true
            } else {
              return false
            }
          }
          
          return {check: check}
        })();


// LS
/**
 * LS With Expired Features
 * key-value 
 * 
 *   key: {value: xx, time: xx}
 * 
 */ 
var LS = (function () {
  var oops = !window.localStorage
  
  if (oops) {console.log('not found localStorage Object.')}
  
  function get (key) {
    if (oops) {return null}
    var str = localStorage.getItem(key), t = +new Date(), obj
    if (str !== null) {
      try {
        obj = JSON.parse(str)
        if (typeof obj.time === 'undefined') {
          return obj.value
        } else {
          if (obj.time > t) {
            return obj.value
          } else {
            return null
          }
        }
      } catch (e) {
        new Error(e)
      }
    } else {
      return null
    }
  }
  
  // time unit: millisecond (ms)
  function set (key, value, time) {
    if (oops) {return}
    var obj = {}, str = ''
    
    if (typeof value === 'undefined') {return}
    
    if (typeof time === 'number') {
      obj = {
        value: value,
        time: +new Date() + time
      }
    } else {
      obj = { value: value }
    }
    
    try {
      localStorage.setItem(key, JSON.stringify(obj))
    } catch (e) {
      localStorage.clear()
      localStorage.setItem(key, JSON.stringify(obj))
    }
  }
  
  function del (key) {
    if (oops) {return}
    
    localStorage.removeItem(key)
  }
  
  return {
    get: get, set: set, del: del
  }
})();


// toast
var toast = (function () {
  var template = '<div class="card-toast-list"></div>',
    isAppend = false,
    list = null

  return {
    add: function (type, text) {
      if (!isAppend) {
        document.body && document.body.insertAdjacentHTML('beforeend', template)
        list = document.body.querySelector('.card-toast-list')
        isAppend = true
      }
      
      if (type === 'undefined') {
        type = 'default'
      }
      
      if (typeof text === 'undefined') {
        text = type
      }
      
      var dom = document.createElement('div')
      dom.setAttribute('class', `toast-item ${type}`)
      dom.innerHTML = text
      list.appendChild(dom)
      setTimeout(function () {
        dom.classList.add('in')
      }, 0)
      
      setTimeout(function () {
        var dom = list.querySelector('.toast-item')
        if (dom) {
          dom.classList.add('reverse')
          setTimeout(function () {
            list.removeChild(list.querySelector('.toast-item'))
          }, 400)
        }
      }, 3000)
    }
  }
})();

// URL Parse
var URLParser = (function () {
    var dom = document.createElement('a')

    function parse (url) {
      dom.href = url
      
      var search = dom.search, params = {}, pathname = dom.pathname,
        domain = dom.host, hostname = dom.hostname, protocol = dom.protocol, hash = dom.hash, port = dom.port
      
      if (search.length > 1) {
        let arr = search.split('?')[1].split('&')
          
        arr.map((item) => {
          var kv = item.split('=')
          
          params[kv[0]] = kv[1]
        })
      }
      
      function getUrl () {
        var item = '', arr = []
          
        for (item in params) {
          arr.push(item + '=' + params[item])
        }
        
        return protocol + '//' + hostname + (port ? ':' + port : '') + pathname + (arr.length >= 1 ? '?' : '') + arr.join('&') + hash
      }
      
      return {
        url: url,
        path: pathname,
        search: search,
        domain: domain,
        hostname: hostname,
        protocol: protocol,
        hash: hash,
        query: function (key) {
          return params[key]
        },
        getParams: function () {
          return params
        },
        getUrl: getUrl,
        addParams: function (data) {
          var item = '', arr = []
          if (typeof data !== 'object') {return}
          
          for (item in data) {
            params[item] = data[item]
          }
          
          return getUrl()
        }
      }
    }
    
    return {parse}
  })();
  

// image handle
function handleImage (file, config, callback) {
  if (!file) {return}
  
  var base64 = '', 
    canvas = document.createElement('canvas'), 
    ctx = canvas.getContext('2d')
  
  if (typeof config === 'function') {
    callback = config
    config = {}
  }
  
  config = $.extend({
    width: 100,
    height: 100,
    q: 0.8
  }, config || {})
  
  canvas.width = config.width
  canvas.height = config.height
  
  var reader = new FileReader()
      
  reader.addEventListener('load', function (e) {
    optimize(e.target.result)
  })
  
  reader.readAsDataURL(file)
  
  function optimize (dataUrl) {
    var img = document.createElement('img')
    img.width = config.width
    img.height = config.height
    img.src = dataUrl
    
    setTimeout(function () {
      ctx.clearRect(0, 0, config.width, config.height)
      ctx.drawImage(img, 0, 0, config.width, config.height)
      
      base64 = canvas.toDataURL(file.type, config.q)
      
      callback && callback(base64)
    }, 0)
  }
}

// subpub
var subpub = (function () {
    var eventMap = {}
    
    function emit () {
      if (arguments.length > 0) {
        var name = arguments[0],
          params = Array.prototype.slice.call(arguments, 1)
        if (eventMap[name]) {
          try {
            eventMap[name].map(function (obj) {
              obj && obj.handler && obj.handler.apply(this, params)
            })
          } catch (e) {
            console.error(`exec event ${name} failed. cardID: ${this.domId}`)
          }
        } else {
          console.warn('can not found event: ' + name + '. cardID: ' + this.domId)
        }
      }
    }
    
    function listen (name, handler) {
      if (typeof name === 'string' && typeof handler === 'function') {
        if (!eventMap[name]) {
          eventMap[name] = []
        }
        eventMap[name].push({
          id: this.domId,
          handler
        })
      }
    }
    
    function clear (id) {
      var name = '', temp = null
      for (name in eventMap) {
        temp = eventMap[name]
        eventMap[name] = temp.map(function (obj) {
          if (obj && obj.id !== id) {
            return obj
          }
        })
      }
    }
    
    return {
      emit, listen, clear
    }
  })();

// copy
function copy (val) {
    var type = Object.prototype.toString.call(val)
    if (type === '[object Array]') {
      return val.slice(0)
    } else if (type === '[object Object]') {
      return $.extend({}, val)
    } else {
      return val
    }
  }

```

```css
/* toast */
.card-toast-list {position: fixed; z-index: 999999; right: 10px; bottom: 10px; width: 300px; height: auto; transform: translateZ(0)}
.card-toast-list .toast-item {width: 200px; text-align: center; border-radius: 10px; padding: 15px 20px; box-sizing: border-box; font-size: 20px; position: relative; margin: 0 0 10px; top: 20px; opacity: 0; transition: top .4s ease-out, opacity .4s ease-out; box-shadow: 1px 1px 3px #000}
.card-toast-list .toast-item.in {top: 0; opacity: .9;}
.card-toast-list .toast-item.in.reverse {top: -20px; opacity: 0}
.card-toast-list .toast-item.default {background: #ccc; color: #fff}
.card-toast-list .toast-item.success {background: #09f; color: #fff}
.card-toast-list .toast-item.error {background: #c66; color: #fff}
.card-toast-list .toast-item.warning {background: #fffbe6; color: #7d612e}
.card-toast-list .toast-item.fail {background: #ff9; color: #333}
```
