### ISSUE TITLE
CSS 小技巧

### ISSUE THREAD

**Issue by ajccom** [ajccom/note#3]
### Chrome 输入框聚焦时背景色修改

```css
input:-webkit-autofill {  -webkit-box-shadow: inset 0 0 0 1000px #fff; background-color: transparent; } ​​​​
```
